steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
  dir: 'functions/autodeploy'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'vad-blir-skatten', '--trigger-http', '--runtime', 'nodejs10', '--entry-point', 'getTaxAmount']
  dir: 'functions/autodeploy'